version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_hospital_db
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    container_name: hospital_app
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_DIALECT=${DB_DIALECT}
      - DB_PORT=${DB_PORT}
    ports:
      - "3000:3000"
    volumes:
      - .:/hospital-appointment-scheduler
      - /hospital-appointment-scheduler/node_modules
    depends_on:
      - db
    command: nodemon index.js

volumes:
 db-data:
