version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_hospital_db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - "3306:3306"

  app:
    build:
      context: .
    container_name: hospital_app
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB_DIALECT: ${DB_DIALECT}
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: npm start
