name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: ${{ secrets.TEST_DB_PASS }}
          POSTGRES_USER: ${{ secrets.TEST_DB_USER }}
          POSTGRES_DB: ${{ secrets.TEST_DB_NAME }}
        ports:
          - 5434:5432
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Start Containers
        run: |
          docker compose up -d
          docker compose exec test npm test

      - name: Stop and remove containers
        run: docker-compose down
